/**
 * MaxsimCLI uninstaller — complete removal of all installed files.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { removeDir } from './copy.js';
import { removeHooks } from './hooks.js';

/** Completely uninstall MaxsimCLI from a project directory. */
export function uninstall(projectDir: string): {
  removedDirs: string[];
  removedFiles: string[];
  cleanedSettings: boolean;
} {
  const claudeDir = path.join(projectDir, '.claude');
  const removedDirs: string[] = [];
  const removedFiles: string[] = [];

  // Remove MaxsimCLI directories
  const dirsToRemove = [
    path.join(claudeDir, 'maxsim'),         // workflows, templates, references, bin, hooks
    path.join(claudeDir, 'commands', 'maxsim'), // slash commands
    path.join(claudeDir, 'agent-memory', 'maxsim-learner'), // agent persistent memory (maxsim only)
  ];

  for (const dir of dirsToRemove) {
    if (fs.existsSync(dir)) {
      removeDir(dir);
      removedDirs.push(dir);
    }
  }

  // Remove agent files
  const agentsDir = path.join(claudeDir, 'agents');
  if (fs.existsSync(agentsDir)) {
    const agentFiles = ['executor.md', 'planner.md', 'researcher.md', 'verifier.md', 'AGENTS.md'];
    for (const file of agentFiles) {
      const filePath = path.join(agentsDir, file);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        removedFiles.push(filePath);
      }
    }
    // Remove agents dir if empty
    try {
      const remaining = fs.readdirSync(agentsDir);
      if (remaining.length === 0) {
        fs.rmdirSync(agentsDir);
        removedDirs.push(agentsDir);
      }
    } catch { /* ignore */ }
  }

  // Remove skill directories
  const skillsDir = path.join(claudeDir, 'skills');
  if (fs.existsSync(skillsDir)) {
    const builtInSkills = [
      'tdd', 'systematic-debugging', 'brainstorming', 'roadmap-writing',
      'handoff-contract', 'commit-conventions', 'maxsim-batch', 'code-review',
      'verification', 'github-operations', 'research', 'project-memory',
      'using-maxsim', 'maxsim-simplify',
    ];
    for (const skill of builtInSkills) {
      const skillDir = path.join(skillsDir, skill);
      if (fs.existsSync(skillDir)) {
        removeDir(skillDir);
        removedDirs.push(skillDir);
      }
    }
  }

  // Remove rules files
  const rulesDir = path.join(claudeDir, 'rules');
  if (fs.existsSync(rulesDir)) {
    const ruleFiles = ['conventions.md', 'verification-protocol.md'];
    for (const file of ruleFiles) {
      const filePath = path.join(rulesDir, file);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
        removedFiles.push(filePath);
      }
    }
  }

  // Remove CLAUDE.md from project root if it was generated by MaxsimCLI
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  if (fs.existsSync(claudeMdPath)) {
    const content = fs.readFileSync(claudeMdPath, 'utf8');
    if (content.includes('MaxsimCLI') || content.includes('maxsim')) {
      fs.unlinkSync(claudeMdPath);
      removedFiles.push(claudeMdPath);
    }
  }

  const settingsPath = path.join(claudeDir, 'settings.json');
  const hadSettings = hasMaxsimSettings(settingsPath);
  removeHooks(projectDir);

  return {
    removedDirs,
    removedFiles,
    cleanedSettings: hadSettings,
  };
}

/** Returns true if settings.json contains maxsim hooks or statusLine. */
function hasMaxsimSettings(settingsPath: string): boolean {
  if (!fs.existsSync(settingsPath)) return false;
  try {
    const s = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    const hasHooks =
      s.hooks &&
      Object.values(s.hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>).some(
        (matchers) => matchers.some((m) => m.hooks.some((h) => h.command.includes('maxsim'))),
      );
    return hasHooks || s.statusLine?.command?.includes('maxsim') === true;
  } catch {
    return false;
  }
}
