/**
 * MaxsimCLI uninstaller — complete removal of all installed files.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { removeDir } from './copy.js';
import { removeHooks } from './hooks.js';
import { removeManifested } from './manifest.js';

/** Completely uninstall MaxsimCLI from a project directory. */
export function uninstall(projectDir: string): {
  removedDirs: string[];
  removedFiles: string[];
  cleanedSettings: boolean;
} {
  const claudeDir = path.join(projectDir, '.claude');
  const removedDirs: string[] = [];
  const removedFiles: string[] = [];

  removeManifested(projectDir);

  // Remove MaxsimCLI directories
  const dirsToRemove = [
    path.join(claudeDir, 'maxsim'),         // workflows, templates, references, bin, hooks
    path.join(claudeDir, 'commands', 'maxsim'), // slash commands
    path.join(claudeDir, 'agent-memory', 'maxsim-learner'), // agent persistent memory (maxsim only)
  ];

  for (const dir of dirsToRemove) {
    if (fs.existsSync(dir)) {
      removeDir(dir);
      removedDirs.push(dir);
    }
  }

  // Remove agents/, skills/, rules/ wholesale
  for (const dir of [
    path.join(claudeDir, 'agents'),
    path.join(claudeDir, 'skills'),
    path.join(claudeDir, 'rules'),
  ]) {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
      removedDirs.push(dir);
    }
  }

  // Remove CLAUDE.md from project root if it was generated by MaxsimCLI
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  if (fs.existsSync(claudeMdPath)) {
    const content = fs.readFileSync(claudeMdPath, 'utf8');
    if (content.includes('MaxsimCLI') || content.includes('maxsim')) {
      fs.unlinkSync(claudeMdPath);
      removedFiles.push(claudeMdPath);
    }
  }

  const settingsPath = path.join(claudeDir, 'settings.json');
  const hadSettings = hasMaxsimSettings(settingsPath);
  removeHooks(projectDir);

  return {
    removedDirs,
    removedFiles,
    cleanedSettings: hadSettings,
  };
}

/** Returns true if settings.json contains maxsim hooks or statusLine. */
function hasMaxsimSettings(settingsPath: string): boolean {
  if (!fs.existsSync(settingsPath)) return false;
  try {
    const s = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    const hasHooks =
      s.hooks &&
      Object.values(s.hooks as Record<string, Array<{ hooks: Array<{ command: string }> }>>).some(
        (matchers) => matchers.some((m) => m.hooks.some((h) => h.command.includes('maxsim'))),
      );
    return hasHooks || s.statusLine?.command?.includes('maxsim') === true;
  } catch {
    return false;
  }
}
