/**
 * GitHub Issues — Phase CRUD, task sub-issues, plan comments, close/reopen
 *
 * Uses Octokit REST API for all operations. Phase Issues have YAML frontmatter
 * bodies. Tasks are linked as native sub-issues via GitHub's sub-issues API.
 * Plans are posted as structured comments on phase Issues.
 *
 * CRITICAL: Uses `child.data.id` (internal numeric ID) for sub-issue linking,
 *   NOT `child.data.number` (human-readable number).
 * CRITICAL: All operations use client.ts (Octokit adapter) exclusively.
 * CRITICAL: Never call process.exit() — return GhResult instead.
 */

import type { GhResult, StateReason } from './types.js';
import { getOctokit, getRepoInfo, withGhResult } from './client.js';

// ---- Phase Issue Creation ---------------------------------------------------

/**
 * Create a GitHub Issue for a MAXSIM phase.
 *
 * Title: `[Phase {phaseNum}] {phaseName}`
 * Body: YAML frontmatter (in ```yaml code fence) + human-readable sections.
 * Label: `phase`
 *
 * Returns both `number` (for display/API) and `id` (for sub-issue linking).
 */
export async function createPhaseIssue(
  phaseNum: string,
  phaseName: string,
  goal: string,
  requirements: string[],
  successCriteria: string[],
): Promise<GhResult<{ number: number; id: number }>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const title = `[Phase ${phaseNum}] ${phaseName}`;

    // Build YAML frontmatter block
    const reqYaml = requirements.length > 0
      ? `\n${requirements.map(r => `  - ${r}`).join('\n')}`
      : ' []';

    const frontmatter = [
      '```yaml',
      `phase_number: "${phaseNum}"`,
      `requirements:${reqYaml}`,
      'dependencies: []',
      "status: 'to-do'",
      '```',
    ].join('\n');

    // Build human-readable sections
    const reqSection = requirements.length > 0
      ? requirements.map(r => `- ${r}`).join('\n')
      : '_None specified_';

    const criteriaSection = successCriteria.length > 0
      ? successCriteria.map(c => `- [ ] ${c}`).join('\n')
      : '_None specified_';

    const body = `${frontmatter}

## Goal

${goal}

## Requirements

${reqSection}

## Success Criteria

${criteriaSection}

---
*Generated by MAXSIM*`;

    const response = await octokit.rest.issues.create({
      owner,
      repo,
      title,
      body,
      labels: ['phase'],
    });

    return {
      number: response.data.number,
      id: response.data.id,
    };
  });
}

// ---- Task Sub-Issue Creation ------------------------------------------------

/**
 * Create a task sub-issue and link it to a parent phase Issue.
 *
 * Title: `[P{phaseNum}] {title}`
 * Label: `task`
 * Body: passed as-is (caller formats it).
 *
 * After creation, links the new issue as a sub-issue of the parent via
 * GitHub's native sub-issues API. Uses `child.data.id` (internal ID),
 * NOT `child.data.number`.
 *
 * If sub-issue linking fails, attempts cleanup by closing the orphan issue.
 */
export async function createTaskSubIssue(
  phaseNum: string,
  taskId: string,
  title: string,
  body: string,
  parentIssueNumber: number,
): Promise<GhResult<{ number: number; id: number }>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const issueTitle = `[P${phaseNum}] ${title}`;

    // Create the child issue
    const child = await octokit.rest.issues.create({
      owner,
      repo,
      title: issueTitle,
      body,
      labels: ['task'],
    });

    // Link as sub-issue using the internal `id` (NOT `number`)
    try {
      await (octokit.rest.issues as any).addSubIssue({
        owner,
        repo,
        issue_number: parentIssueNumber,
        sub_issue_id: child.data.id,
      });
    } catch (linkError: unknown) {
      // Sub-issue linking failed — attempt cleanup by closing the orphan
      try {
        await octokit.rest.issues.update({
          owner,
          repo,
          issue_number: child.data.number,
          state: 'closed',
          state_reason: 'not_planned' as any,
        });
      } catch {
        // Cleanup failed — orphan issue will remain open
      }

      const message = linkError instanceof Error ? linkError.message : String(linkError);
      throw new Error(
        `Created issue #${child.data.number} but failed to link as sub-issue: ${message}. ` +
        `Orphan issue has been closed.`
      );
    }

    return {
      number: child.data.number,
      id: child.data.id,
    };
  });
}

// ---- Plan Comments ----------------------------------------------------------

/**
 * Post a structured plan comment on a phase Issue.
 *
 * Comment body: `## Plan {planNumber}\n\n{planContent}\n\n---\n*Posted by MAXSIM*`
 */
export async function postPlanComment(
  phaseIssueNumber: number,
  planNumber: string,
  planContent: string,
): Promise<GhResult<{ commentId: number }>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const commentBody = `## Plan ${planNumber}\n\n${planContent}\n\n---\n*Posted by MAXSIM*`;

    const response = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: phaseIssueNumber,
      body: commentBody,
    });

    return { commentId: response.data.id };
  });
}

// ---- Issue Lifecycle --------------------------------------------------------

/**
 * Close an issue. Optionally post a reason comment before closing.
 *
 * @param stateReason - 'completed' (default) or 'not_planned' (rollback/cancel)
 */
export async function closeIssue(
  issueNumber: number,
  reason?: string,
  stateReason: StateReason = 'completed',
): Promise<GhResult<void>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    // If a reason is provided, post it as a comment before closing
    if (reason) {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: issueNumber,
        body: reason,
      });
    }

    await octokit.rest.issues.update({
      owner,
      repo,
      issue_number: issueNumber,
      state: 'closed',
      state_reason: stateReason as any,
    });
  });
}

/**
 * Reopen a closed issue.
 */
export async function reopenIssue(issueNumber: number): Promise<GhResult<void>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    await octokit.rest.issues.update({
      owner,
      repo,
      issue_number: issueNumber,
      state: 'open',
    });
  });
}

// ---- Issue Fetch ------------------------------------------------------------

/**
 * Fetch a single issue by number.
 *
 * Returns number, id, title, state, body, updated_at, labels, and comments_url.
 */
export async function getPhaseIssue(
  phaseIssueNumber: number,
): Promise<GhResult<{
  number: number;
  id: number;
  title: string;
  state: string;
  body: string;
  updated_at: string;
  labels: string[];
  comments_url: string;
}>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const response = await octokit.rest.issues.get({
      owner,
      repo,
      issue_number: phaseIssueNumber,
    });

    const labels = response.data.labels.map(l =>
      typeof l === 'string' ? l : (l.name ?? ''),
    ).filter(Boolean);

    return {
      number: response.data.number,
      id: response.data.id,
      title: response.data.title,
      state: response.data.state,
      body: response.data.body ?? '',
      updated_at: response.data.updated_at,
      labels,
      comments_url: response.data.comments_url,
    };
  });
}

/**
 * List all sub-issues of a phase Issue.
 *
 * Uses GitHub's native sub-issues API.
 * Returns each sub-issue's number, id, title, state, and updated_at.
 */
export async function listPhaseSubIssues(
  phaseIssueNumber: number,
): Promise<GhResult<Array<{ number: number; id: number; title: string; state: string; updated_at: string }>>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const response = await (octokit.rest.issues as any).listSubIssues({
      owner,
      repo,
      issue_number: phaseIssueNumber,
    });

    const subIssues = (response.data as any[]).map((issue: any) => ({
      number: issue.number as number,
      id: issue.id as number,
      title: issue.title as string,
      state: issue.state as string,
      updated_at: (issue.updated_at as string) ?? '',
    }));

    return subIssues;
  });
}

// ---- Generic Comment --------------------------------------------------------

/**
 * Post a generic comment on a GitHub issue.
 *
 * Used by MCP tools for blocker linking, bounce feedback, etc.
 */
export async function postComment(
  issueNumber: number,
  body: string,
): Promise<GhResult<{ commentId: number }>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const response = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body,
    });

    return { commentId: response.data.id };
  });
}

// ---- Completion Comment -----------------------------------------------------

/**
 * Post a structured completion comment on an issue.
 *
 * Includes the commit SHA and list of files changed.
 * Satisfies CONTEXT.md decision: "Each completed task gets a completion comment."
 */
export async function postCompletionComment(
  issueNumber: number,
  commitSha: string,
  filesChanged: string[],
): Promise<GhResult<{ commentId: number }>> {
  return withGhResult(async () => {
    const octokit = getOctokit();
    const { owner, repo } = await getRepoInfo();

    const fileList = filesChanged.length > 0
      ? filesChanged.map(f => `- \`${f}\``).join('\n')
      : '_No files changed_';

    const commentBody = `## Task Completed

**Commit:** \`${commitSha}\`

### Files Changed
${fileList}

---
*Completion recorded by MAXSIM*`;

    const response = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: commentBody,
    });

    return { commentId: response.data.id };
  });
}
